sections = [
    {'section_id': '1', 'name': 'Куплю | Продам', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D0%BA%D1%83%D0%BF%D0%BB%D1%8E-%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%BC/"},
    {'section_id': '1', 'name': 'Kauf, Verkauf', 'lang': 'de',
         'url': "https://anzeigen.ru-geld.de/de/goods/"}
]

sections2 = [
    {'section_id': '1', 'name': 'Куплю | Продам', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D0%BA%D1%83%D0%BF%D0%BB%D1%8E-%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%BC/"},
    {'section_id': '2', 'name': 'Услуги', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B8/"},
    {'section_id': '3', 'name': 'Работа', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0/"},
    {'section_id': '4', 'name': 'Бизнес', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81/"},
    {'section_id': '5', 'name': 'Розыск', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D1%80%D0%BE%D0%B7%D1%8B%D1%81%D0%BA/"},
    {'section_id': '6', 'name': 'Здоровье', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D0%B7%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D1%8C%D0%B5/"},
    {'section_id': '7', 'name': 'Отдых', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D0%BE%D1%82%D0%B4%D1%8B%D1%85/"},
    {'section_id': '8', 'name': 'Недвижимость', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D0%BD%D0%B5%D0%B4%D0%B2%D0%B8%D0%B6%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C/"},
    {'section_id': '9', 'name': 'Отдам бесплатно', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D0%B2-%D0%B4%D0%B0%D1%80/"},
    {'section_id': '10', 'name': 'События', 'lang': 'ru',
     'url': "https://anzeigen.ru-geld.de/%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D1%8F/"},

    {'section_id': '1', 'name': 'Kauf, Verkauf', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/goods/"},
    {'section_id': '2', 'name': 'Dienstleistungen', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/services/"},
    {'section_id': '3', 'name': 'Arbeit', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/job/"},
    {'section_id': '4', 'name': 'Business', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/business/"},
    {'section_id': '5', 'name': 'Fundstelle', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/lost-and-found/"},
    {'section_id': '6', 'name': 'Gesundheit', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/health/"},
    {'section_id': '7', 'name': 'Urlaub, Reise', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/travel/"},
    {'section_id': '8', 'name': 'Immobilien', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/real-estate/"},
    {'section_id': '9', 'name': 'Zu Verschenken', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/give-away/"},
    {'section_id': '10', 'name': 'Veranstaltungen', 'lang': 'de',
     'url': "https://anzeigen.ru-geld.de/de/events/"}
]